### ISSUE TITLE
composer

### ISSUE THREAD

**Issue by netdust** [wunderio/docebo-php#3]
I can't seem to install this package using composer. composer says it can't find a matching version of the package. what can i do to install this?

**Comment by notoriousturtle** [comment]
Yeah, any chance you could fix this asap?

**Comment by artisba** [comment]
To install via composer you'll have to define this an additional repository in your composer.json:
```
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/wunderio/docebo-php"
    }
]
